# Generated by Django 3.1.6 on 2021-02-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, height_field=300, upload_to='news_media', width_field=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='rubric',
            field=models.ManyToManyField(blank=True, related_name='news', to='engine.Rubrics'),
        ),
    ]
