# Generated by Django 3.1.6 on 2021-02-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20210210_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, unique=True, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('photo', models.ImageField(upload_to='profile_photos', verbose_name='Фото профиля')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rubrics',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название рубрики'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ManyToManyField(related_name='authors', to='engine.Authors'),
        ),
    ]
