# Generated by Django 3.1.6 on 2021-02-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20210217_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='author',
            new_name='authors',
        ),
    ]
