# Generated by Django 3.1.6 on 2021-02-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20210217_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, unique=True),
        ),
    ]
