# Generated by Django 3.1.6 on 2021-02-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20210217_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='authors',
            field=models.ManyToManyField(related_name='authors_of_news', to='engine.Authors'),
        ),
    ]
